# Generated by Django 4.1.6 on 2023-02-10 00:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("libreria", "0002_libros"),
    ]

    operations = [
        migrations.DeleteModel(
            name="libros",
        ),
    ]
